//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2019
    {
        public string ppp { get; set; }
        public int JAN { get; set; }
        public int FEB { get; set; }
        public int MAR { get; set; }
        public int APR { get; set; }
        public int MAY { get; set; }
        public int JUN { get; set; }
        public int JUL { get; set; }
        public int AUG { get; set; }
        public int SEP { get; set; }
        public int OCT { get; set; }
        public int NOV { get; set; }
        public int DEC { get; set; }
    }
}
