//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WiseMachineEntities : DbContext
    {
        public WiseMachineEntities()
            : base("name=WiseMachineEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpDb> EmpDb { get; set; }
        public virtual DbSet<ItemDb> ItemDb { get; set; }
        public virtual DbSet<MachineDb> MachineDb { get; set; }
        public virtual DbSet<MachineStorageDb> MachineStorageDb { get; set; }
        public virtual DbSet<SalesStatisticsDb> SalesStatisticsDb { get; set; }
        public virtual DbSet<WareHouseDb> WareHouseDb { get; set; }
        public virtual DbSet<WareHouseStorageDb> WareHouseStorageDb { get; set; }
        public virtual DbSet<api2019> api2019 { get; set; }
        public virtual DbSet<MachineStorageView> MachineStorageView { get; set; }
        public virtual DbSet<WareHouseStorageView> WareHouseStorageView { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<alltable> alltable { get; set; }
        public virtual DbSet<LastMonthApi> LastMonthApi { get; set; }
        public virtual DbSet<LastSenvenDaysApi> LastSenvenDaysApi { get; set; }
    }
}
